import type { Metadata } from "next";
import { Pattaya, Ubuntu } from "next/font/google";
import "./globals.css";
import { TelegramProvider } from "@/app/providers/TelegramProvider";
import Script from "next/script";
import { Header } from "@/widgets/ui/header/Header";
import { NavigateTabs } from "@/widgets/ui/navigate-tabs/NavigateTabs";

const getPattaya = Pattaya({
  variable: "--font-pattaya",
  weight: "400",
});

const getUbuntu = Ubuntu({
  variable: "--font-ubuntu",
  weight: ["400", "300", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script src="https://telegram.org/js/telegram-web-app.js"></Script>
      </head>
      <body
        className={`${getPattaya.variable} ${getUbuntu.variable} antialiased bg-linear-to-bl from-violet-500 to-fuchsia-500 min-h-screen `}
      >
        <TelegramProvider>
          <Header />
          {children}
          <NavigateTabs />
        </TelegramProvider>
      </body>
    </html>
  );
}
